try {
    throw Error('Practicing throwing');
  } catch (e) {
    console.log(e);
  }